In [1]:
# Import library
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv("supplement.csv")
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [10]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [11]:
dataset.describe()

Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [17]:
dataset.tail()

ID  Store_id Store_Type Location_Type Region_Code        Date  \
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00

In [15]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import plotly.express as px

In [25]:
store_type = dataset["Store_Type"].value_counts()
store_index = store_type.index
store_orders = store_type.values

pie_fig1 = px.pie(dataset, values=store_orders, names =store_index)
pie_fig1.show()

In [23]:
loc_type = dataset["Location_Type"].value_counts()
loc_index = loc_type.index
loc_orders = loc_type.values

pie_fig1 = px.pie(dataset, values=loc_orders, names =loc_index)
pie_fig1.show()

In [32]:
dataset["Discount"] = dataset["Discount"].map({"No" : 0, "Yes" : 1})

In [33]:
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
188335        1         1      51  37272.00  
188336        1         0      90  54572.64  
188337        1         0      56  31624.56  
188338        1         1      70  49162.41  
188339        1         0      47  37977.00  

[188340 rows x 10 columns]

In [34]:
dataset["Store_Type"] = dataset["Store_Type"].map({"S1" : 0, "S2" : 1, "S3" :3, "S4" : 4})

In [35]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1" : 0, "L2" : 1, "L3" :3, "L4" : 4})

In [41]:
reg_code=dataset["Region_Code"].value_counts()
reg_code

Region_Code
R1    63984
R2    54180
R3    44376
R4    25800
Name: count, dtype: int64

In [42]:
dataset["Region_Code"] = dataset["Region_Code"].map({"R1" : 0, "R2" : 1, "R3" :3, "R4" : 4})

In [52]:
x = np.array(dataset[["Store_Type","Location_Type","Region_Code","Discount","Holiday"]])
y = np.array(dataset["#Order"])

In [53]:
x

array([[0., 3., 0., 1., 1.],
       [4., 1., 0., 1., 1.],
       [3., 1., 0., 1., 1.],
       ...,
       [0., 3., 1., 0., 1.],
       [3., 0., 1., 1., 1.],
       [1., 0., 0., 0., 1.]])

In [54]:
y

array([ 9, 60, 42, ..., 56, 70, 47])

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=42)

In [57]:
len(x_train), len(x_test), len(dataset)

(150672, 37668, 188340)

In [58]:
pip install lightgbm


   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.4 MB 495.5 kB/s eta 0:00:03
   - -------------------------------------- 0.1/1.4 MB 550.5 kB/s eta 0:00:03
   --- ------------------------------------ 0.1/1.4 MB 853.3 kB/s eta 0:00:02
   ----- ---------------------------------- 0.2/1.4 MB 958.4 kB/s eta 0:00:02
   ------- -------------------------------- 0.3/1.4 MB 1.2 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.4 MB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.4 MB 1.5 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.4 MB 1.5 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.4 MB 1.2 MB/s eta 0:00:01
   -------------------- ------------------- 0.7/1.4 MB 1.4 MB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.4 MB 1.7 MB/s eta 0:00:01
   ---------------


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [60]:
import lightgbm as lgb

In [61]:
model = lgb.LGBMRegressor()

In [63]:
model.fit(x_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001930 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 17
[LightGBM] [Info] Number of data points in the train set: 150672, number of used features: 5
[LightGBM] [Info] Start training from score 68.163401


LGBMRegressor()

In [64]:
y_pred = model.predict(x_test)

In [65]:
y_pred, y_test

(array([ 50.20021682, 104.3184055 ,  68.10874469, ...,  45.28700943,
         62.52625355,  84.79576054]),
 array([ 54, 111,  59, ...,  40,  69,  68]))

In [66]:
model.score(x_test, y_test)

0.613902007760576